# Generated by Django 4.2.16 on 2024-10-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('service', models.CharField(choices=[('GM', 'Gmail'), ('YA', 'Yandex'), ('MA', 'Mail')], max_length=3)),
                ('email_from', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date_sent', models.DateTimeField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('uid', 'service')},
            },
        ),
        migrations.CreateModel(
            name='TargetEmail',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('server', models.CharField(choices=[('imap.gmail.com', 'Gmail'), ('imap.yandex.ru', 'Yandex'), ('imap.mail.ru', 'Mail')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmailMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='email_reader.emailmessage')),
            ],
        ),
    ]
