services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "email_reader"
    ports:
      - "5432:5432"

  django_application:
    container_name: django_application
    build:
      context: ./comsoftlab
    ports:
      - "8001:8000"
    env_file:
      - conf/.env
    volumes:
      - static-files:/django_app/static
      - media-files:/django_app/media
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static-files:/static
      - media-files:/media
    depends_on:
      - django_application

volumes:
  static-files:
  media-files: